import { z } from "zod";

export const updateSettingsSchema = z.object({
  whatsappNumber: z.string().optional(),
  bannerMessage: z.string().optional(),
  bannerLink: z.string().url().optional().or(z.literal("")),
  bannerActive: z.boolean().optional(),
  freeShippingThreshold: z.number().min(0).optional(),
  shippingFee: z.number().min(0).optional(),
  taxRate: z.number().min(0).max(100).optional(),
  primaryColor: z.string().optional(),
  secondaryColor: z.string().optional(),
  accentColor: z.string().optional(),
  cookiesPolicy: z.string().optional(),
  privacyPolicy: z.string().optional(),
  termsOfService: z.string().optional(),
  aboutUs: z.string().optional(),
  careers: z.string().optional(),
  faqs: z.string().optional(),
  shippingPolicy: z.string().optional(),
  returnsPolicy: z.string().optional(),
  heroImages: z.array(z.string()).optional(),
  businessAddress: z.object({
    name: z.string().optional(),
    phone: z.string().optional(),
    phone2: z.string().optional(),
    line1: z.string().optional(),
    line2: z.string().optional(),
    city: z.string().optional(),
    state: z.string().optional(),
    pincode: z.string().optional(),
    email: z.string().optional(),
    email2: z.string().optional(),
    hoursWeekdays: z.string().optional(),
    hoursSunday: z.string().optional(),
  }).optional(),
});
